### ISSUE TITLE
Status of Repo

### ISSUE THREAD

**Issue by ahwillia** [joefowler/DynamicTimeWarp.jl#5]
I'm opening this to check-in on the status of development on this package. I'm interested in extending this package for future use, and I think it would be nice for Julia to have an actively maintained repo supporting DTW.

If I open PRs here will they be reviewed? Or would it be preferable for me to start a new repo and use this as a starting point (with accreditation)? 

Perhaps the ideal situation would be for this to be included under the [JuliaDSP](https://github.com/JuliaDSP) umbrella so that PRs can be reviewed by a larger community? cc @jfsantos @simonster

**Edit:** I wrote this in a bit of haste. I realized after the fact that the tone sounds a bit unappreciative. That was unintentional - I really like this package, but would love to give it some major updates! In the past, I've been in the frustrating situation of trying to work with people who have abandoned their packages (or at least aren't communicative). Just trying to avoid that.

**Comment by joefowler** [comment]
Hey there. I _just_ started a 10-day vacation a few hours ago. So I might be uncommunicative and might appear to have abandoned the package. I agree that sounds frustrating.

I agree that it would be great to include more features, and your idea of including this work in a broader package might best serve the goal of getting pull requests reviewed. I'm just a scientist with a lot of competing activities and demands. (And I'm not yet the julia expert that I want to be someday.)

Let me read about JuliaDSP, but I won't be able to focus much until mid-August. Thanks for your interest.

-Joe

**Comment by ahwillia** [comment]
Enjoy your vacation! When you get back, take a look at my fork here: https://github.com/ahwillia/DynamicTimeWarp.jl

I'd be happy to open a PR. Or, if you wanted to give me push access, I could merge and help maintain the package (although I'm also a busy scientist juggling projects). We should get it registered somewhat soon as well, unless maybe the JuliaDSP folks have other ideas.

**Comment by joefowler** [comment]
Dear Alex,

Thanks so much for your interest in using (and awesome-ifying) the Julia DTW package. I was on vacation these last 10 days and have not had a chance to look over your work until today. Well, to be honest, I have not had much change today, either.

You suggested me giving you push access and working together to maintain the package. That sounds like a good idea, especially if you could pursue either getting it into METADATA or merging with another, larger package. On the other hand, I'm half inclined to suggest that we declare _your_ fork as the new, canonical version before proposing it for METADATA registration. Then you get to be the public face (more importantly to me, the public _voice_) of the project. I'd want to be an assistant maintainer, at least.

**Comment by ahwillia** [comment]
> I'm half inclined to suggest that we declare your fork as the new, canonical version before proposing it for METADATA registration. Then you get to be the public face (more importantly to me, the public voice) of the project.

This works for me. Was trying to tread lightly and not step on toes, but if this is your preferred outcome I'm happy to set this up.

>  I'd want to be an assistant maintainer, at least.

Absolutely. Let's say I close the PR and I'll start a new repo `TimeWarp.jl` -- I'll give you push access. The new name will ensure that there aren't any conflicts/confusion between the two packages. (Plus I like the brevity of it).
